package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblanimais generated by hbm2java
 */
public class Tblanimais  implements java.io.Serializable {


     private Integer codAni;
     private String nomeAni;
     private String descricaoAni;
     private String tipoAni;
     private Date dataNasc;
     private Integer idadeAni;

    public Tblanimais() {
    }

    public Tblanimais(String nomeAni, String descricaoAni, String tipoAni, Date dataNasc, Integer idadeAni) {
       this.nomeAni = nomeAni;
       this.descricaoAni = descricaoAni;
       this.tipoAni = tipoAni;
       this.dataNasc = dataNasc;
       this.idadeAni = idadeAni;
    }
   
    public Integer getCodAni() {
        return this.codAni;
    }
    
    public void setCodAni(Integer codAni) {
        this.codAni = codAni;
    }
    public String getNomeAni() {
        return this.nomeAni;
    }
    
    public void setNomeAni(String nomeAni) {
        this.nomeAni = nomeAni;
    }
    public String getDescricaoAni() {
        return this.descricaoAni;
    }
    
    public void setDescricaoAni(String descricaoAni) {
        this.descricaoAni = descricaoAni;
    }
    public String getTipoAni() {
        return this.tipoAni;
    }
    
    public void setTipoAni(String tipoAni) {
        this.tipoAni = tipoAni;
    }
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }
    public Integer getIdadeAni() {
        return this.idadeAni;
    }
    
    public void setIdadeAni(Integer idadeAni) {
        this.idadeAni = idadeAni;
    }




}


