package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblcontasrecebe generated by hbm2java
 */
public class Tblcontasrecebe  implements java.io.Serializable {


     private Integer codConta;
     private Date dataInicial;
     private Date dataFinal;
     private String nomeCli;
     private Float valorTotalReceb;

    public Tblcontasrecebe() {
    }

    public Tblcontasrecebe(Date dataInicial, Date dataFinal, String nomeCli, Float valorTotalReceb) {
       this.dataInicial = dataInicial;
       this.dataFinal = dataFinal;
       this.nomeCli = nomeCli;
       this.valorTotalReceb = valorTotalReceb;
    }
   
    public Integer getCodConta() {
        return this.codConta;
    }
    
    public void setCodConta(Integer codConta) {
        this.codConta = codConta;
    }
    public Date getDataInicial() {
        return this.dataInicial;
    }
    
    public void setDataInicial(Date dataInicial) {
        this.dataInicial = dataInicial;
    }
    public Date getDataFinal() {
        return this.dataFinal;
    }
    
    public void setDataFinal(Date dataFinal) {
        this.dataFinal = dataFinal;
    }
    public String getNomeCli() {
        return this.nomeCli;
    }
    
    public void setNomeCli(String nomeCli) {
        this.nomeCli = nomeCli;
    }
    public Float getValorTotalReceb() {
        return this.valorTotalReceb;
    }
    
    public void setValorTotalReceb(Float valorTotalReceb) {
        this.valorTotalReceb = valorTotalReceb;
    }




}


