package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA



/**
 * Tblclientes generated by hbm2java
 */
public class Tblclientes  implements java.io.Serializable {


     private Integer codCli;
     private String nomeCli;
     private String enderecoCli;
     private String numCli;
     private String bairroCli;
     private String cidadeCli;
     private Integer ufCli;
     private String fone1cli;
     private String fone2cli;
     private String fone3cli;
     private String fone4cli;

    public Tblclientes() {
    }

    public Tblclientes(String nomeCli, String enderecoCli, String numCli, String bairroCli, String cidadeCli, Integer ufCli, String fone1cli, String fone2cli, String fone3cli, String fone4cli) {
       this.nomeCli = nomeCli;
       this.enderecoCli = enderecoCli;
       this.numCli = numCli;
       this.bairroCli = bairroCli;
       this.cidadeCli = cidadeCli;
       this.ufCli = ufCli;
       this.fone1cli = fone1cli;
       this.fone2cli = fone2cli;
       this.fone3cli = fone3cli;
       this.fone4cli = fone4cli;
    }
   
    public Integer getCodCli() {
        return this.codCli;
    }
    
    public void setCodCli(Integer codCli) {
        this.codCli = codCli;
    }
    public String getNomeCli() {
        return this.nomeCli;
    }
    
    public void setNomeCli(String nomeCli) {
        this.nomeCli = nomeCli;
    }
    public String getEnderecoCli() {
        return this.enderecoCli;
    }
    
    public void setEnderecoCli(String enderecoCli) {
        this.enderecoCli = enderecoCli;
    }
    public String getNumCli() {
        return this.numCli;
    }
    
    public void setNumCli(String numCli) {
        this.numCli = numCli;
    }
    public String getBairroCli() {
        return this.bairroCli;
    }
    
    public void setBairroCli(String bairroCli) {
        this.bairroCli = bairroCli;
    }
    public String getCidadeCli() {
        return this.cidadeCli;
    }
    
    public void setCidadeCli(String cidadeCli) {
        this.cidadeCli = cidadeCli;
    }
    public Integer getUfCli() {
        return this.ufCli;
    }
    
    public void setUfCli(Integer ufCli) {
        this.ufCli = ufCli;
    }
    public String getFone1cli() {
        return this.fone1cli;
    }
    
    public void setFone1cli(String fone1cli) {
        this.fone1cli = fone1cli;
    }
    public String getFone2cli() {
        return this.fone2cli;
    }
    
    public void setFone2cli(String fone2cli) {
        this.fone2cli = fone2cli;
    }
    public String getFone3cli() {
        return this.fone3cli;
    }
    
    public void setFone3cli(String fone3cli) {
        this.fone3cli = fone3cli;
    }
    public String getFone4cli() {
        return this.fone4cli;
    }
    
    public void setFone4cli(String fone4cli) {
        this.fone4cli = fone4cli;
    }




}


