package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblitensvacinas generated by hbm2java
 */
public class Tblitensvacinas  implements java.io.Serializable {


     private Integer codItemVacina;
     private int tblAnimaisCodAni;
     private int tblVacinasCodVacina;
     private String nomeItemVacina;
     private Date dataAplic;
     private String descrUltVacina;
     private Date dataProxAplic;
     private String descrProxVacina;

    public Tblitensvacinas() {
    }

	
    public Tblitensvacinas(int tblAnimaisCodAni, int tblVacinasCodVacina) {
        this.tblAnimaisCodAni = tblAnimaisCodAni;
        this.tblVacinasCodVacina = tblVacinasCodVacina;
    }
    public Tblitensvacinas(int tblAnimaisCodAni, int tblVacinasCodVacina, String nomeItemVacina, Date dataAplic, String descrUltVacina, Date dataProxAplic, String descrProxVacina) {
       this.tblAnimaisCodAni = tblAnimaisCodAni;
       this.tblVacinasCodVacina = tblVacinasCodVacina;
       this.nomeItemVacina = nomeItemVacina;
       this.dataAplic = dataAplic;
       this.descrUltVacina = descrUltVacina;
       this.dataProxAplic = dataProxAplic;
       this.descrProxVacina = descrProxVacina;
    }
   
    public Integer getCodItemVacina() {
        return this.codItemVacina;
    }
    
    public void setCodItemVacina(Integer codItemVacina) {
        this.codItemVacina = codItemVacina;
    }
    public int getTblAnimaisCodAni() {
        return this.tblAnimaisCodAni;
    }
    
    public void setTblAnimaisCodAni(int tblAnimaisCodAni) {
        this.tblAnimaisCodAni = tblAnimaisCodAni;
    }
    public int getTblVacinasCodVacina() {
        return this.tblVacinasCodVacina;
    }
    
    public void setTblVacinasCodVacina(int tblVacinasCodVacina) {
        this.tblVacinasCodVacina = tblVacinasCodVacina;
    }
    public String getNomeItemVacina() {
        return this.nomeItemVacina;
    }
    
    public void setNomeItemVacina(String nomeItemVacina) {
        this.nomeItemVacina = nomeItemVacina;
    }
    public Date getDataAplic() {
        return this.dataAplic;
    }
    
    public void setDataAplic(Date dataAplic) {
        this.dataAplic = dataAplic;
    }
    public String getDescrUltVacina() {
        return this.descrUltVacina;
    }
    
    public void setDescrUltVacina(String descrUltVacina) {
        this.descrUltVacina = descrUltVacina;
    }
    public Date getDataProxAplic() {
        return this.dataProxAplic;
    }
    
    public void setDataProxAplic(Date dataProxAplic) {
        this.dataProxAplic = dataProxAplic;
    }
    public String getDescrProxVacina() {
        return this.descrProxVacina;
    }
    
    public void setDescrProxVacina(String descrProxVacina) {
        this.descrProxVacina = descrProxVacina;
    }




}


