package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblitensvendas generated by hbm2java
 */
public class Tblitensvendas  implements java.io.Serializable {


     private Integer codItemVenda;
     private int tblVendasCodVenda;
     private int tblProdutosCodProd;
     private String tipoProdVenda;
     private Float totalVendaProd;
     private Float quantidadeProd;
     private Float precoUniProd;
     private String tipoUni;
     private Date dataVendaProd;

    public Tblitensvendas() {
    }

	
    public Tblitensvendas(int tblVendasCodVenda, int tblProdutosCodProd) {
        this.tblVendasCodVenda = tblVendasCodVenda;
        this.tblProdutosCodProd = tblProdutosCodProd;
    }
    public Tblitensvendas(int tblVendasCodVenda, int tblProdutosCodProd, String tipoProdVenda, Float totalVendaProd, Float quantidadeProd, Float precoUniProd, String tipoUni, Date dataVendaProd) {
       this.tblVendasCodVenda = tblVendasCodVenda;
       this.tblProdutosCodProd = tblProdutosCodProd;
       this.tipoProdVenda = tipoProdVenda;
       this.totalVendaProd = totalVendaProd;
       this.quantidadeProd = quantidadeProd;
       this.precoUniProd = precoUniProd;
       this.tipoUni = tipoUni;
       this.dataVendaProd = dataVendaProd;
    }
   
    public Integer getCodItemVenda() {
        return this.codItemVenda;
    }
    
    public void setCodItemVenda(Integer codItemVenda) {
        this.codItemVenda = codItemVenda;
    }
    public int getTblVendasCodVenda() {
        return this.tblVendasCodVenda;
    }
    
    public void setTblVendasCodVenda(int tblVendasCodVenda) {
        this.tblVendasCodVenda = tblVendasCodVenda;
    }
    public int getTblProdutosCodProd() {
        return this.tblProdutosCodProd;
    }
    
    public void setTblProdutosCodProd(int tblProdutosCodProd) {
        this.tblProdutosCodProd = tblProdutosCodProd;
    }
    public String getTipoProdVenda() {
        return this.tipoProdVenda;
    }
    
    public void setTipoProdVenda(String tipoProdVenda) {
        this.tipoProdVenda = tipoProdVenda;
    }
    public Float getTotalVendaProd() {
        return this.totalVendaProd;
    }
    
    public void setTotalVendaProd(Float totalVendaProd) {
        this.totalVendaProd = totalVendaProd;
    }
    public Float getQuantidadeProd() {
        return this.quantidadeProd;
    }
    
    public void setQuantidadeProd(Float quantidadeProd) {
        this.quantidadeProd = quantidadeProd;
    }
    public Float getPrecoUniProd() {
        return this.precoUniProd;
    }
    
    public void setPrecoUniProd(Float precoUniProd) {
        this.precoUniProd = precoUniProd;
    }
    public String getTipoUni() {
        return this.tipoUni;
    }
    
    public void setTipoUni(String tipoUni) {
        this.tipoUni = tipoUni;
    }
    public Date getDataVendaProd() {
        return this.dataVendaProd;
    }
    
    public void setDataVendaProd(Date dataVendaProd) {
        this.dataVendaProd = dataVendaProd;
    }




}


