package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblleite generated by hbm2java
 */
public class Tblleite  implements java.io.Serializable {


     private Integer codLeite;
     private Date dataTiradoLeite;
     private Float quantidadeLeite;

    public Tblleite() {
    }

    public Tblleite(Date dataTiradoLeite, Float quantidadeLeite) {
       this.dataTiradoLeite = dataTiradoLeite;
       this.quantidadeLeite = quantidadeLeite;
    }
   
    public Integer getCodLeite() {
        return this.codLeite;
    }
    
    public void setCodLeite(Integer codLeite) {
        this.codLeite = codLeite;
    }
    public Date getDataTiradoLeite() {
        return this.dataTiradoLeite;
    }
    
    public void setDataTiradoLeite(Date dataTiradoLeite) {
        this.dataTiradoLeite = dataTiradoLeite;
    }
    public Float getQuantidadeLeite() {
        return this.quantidadeLeite;
    }
    
    public void setQuantidadeLeite(Float quantidadeLeite) {
        this.quantidadeLeite = quantidadeLeite;
    }




}


