package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA



/**
 * Tblprodutos generated by hbm2java
 */
public class Tblprodutos  implements java.io.Serializable {


     private Integer codProd;
     private String tipoProd;
     private String descricaoProd;

    public Tblprodutos() {
    }

    public Tblprodutos(String tipoProd, String descricaoProd) {
       this.tipoProd = tipoProd;
       this.descricaoProd = descricaoProd;
    }
   
    public Integer getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(Integer codProd) {
        this.codProd = codProd;
    }
    public String getTipoProd() {
        return this.tipoProd;
    }
    
    public void setTipoProd(String tipoProd) {
        this.tipoProd = tipoProd;
    }
    public String getDescricaoProd() {
        return this.descricaoProd;
    }
    
    public void setDescricaoProd(String descricaoProd) {
        this.descricaoProd = descricaoProd;
    }




}


