package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA



/**
 * Tbltema generated by hbm2java
 */
public class Tbltema  implements java.io.Serializable {


     private Integer codTema;
     private String nomeTema;

    public Tbltema() {
    }

    public Tbltema(String nomeTema) {
       this.nomeTema = nomeTema;
    }
   
    public Integer getCodTema() {
        return this.codTema;
    }
    
    public void setCodTema(Integer codTema) {
        this.codTema = codTema;
    }
    public String getNomeTema() {
        return this.nomeTema;
    }
    
    public void setNomeTema(String nomeTema) {
        this.nomeTema = nomeTema;
    }




}


