package projetotcc.tabelas;
// Generated 18/06/2012 14:06:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblvendas generated by hbm2java
 */
public class Tblvendas  implements java.io.Serializable {


     private Integer codVenda;
     private int tblClientesCodCli;
     private Float totalVenda;
     private String nomeCli;
     private Date vencimentoVenda;
     private Float pagoVenda;
     private Float saldoVenda;

    public Tblvendas() {
    }

	
    public Tblvendas(int tblClientesCodCli) {
        this.tblClientesCodCli = tblClientesCodCli;
    }
    public Tblvendas(int tblClientesCodCli, Float totalVenda, String nomeCli, Date vencimentoVenda, Float pagoVenda, Float saldoVenda) {
       this.tblClientesCodCli = tblClientesCodCli;
       this.totalVenda = totalVenda;
       this.nomeCli = nomeCli;
       this.vencimentoVenda = vencimentoVenda;
       this.pagoVenda = pagoVenda;
       this.saldoVenda = saldoVenda;
    }
   
    public Integer getCodVenda() {
        return this.codVenda;
    }
    
    public void setCodVenda(Integer codVenda) {
        this.codVenda = codVenda;
    }
    public int getTblClientesCodCli() {
        return this.tblClientesCodCli;
    }
    
    public void setTblClientesCodCli(int tblClientesCodCli) {
        this.tblClientesCodCli = tblClientesCodCli;
    }
    public Float getTotalVenda() {
        return this.totalVenda;
    }
    
    public void setTotalVenda(Float totalVenda) {
        this.totalVenda = totalVenda;
    }
    public String getNomeCli() {
        return this.nomeCli;
    }
    
    public void setNomeCli(String nomeCli) {
        this.nomeCli = nomeCli;
    }
    public Date getVencimentoVenda() {
        return this.vencimentoVenda;
    }
    
    public void setVencimentoVenda(Date vencimentoVenda) {
        this.vencimentoVenda = vencimentoVenda;
    }
    public Float getPagoVenda() {
        return this.pagoVenda;
    }
    
    public void setPagoVenda(Float pagoVenda) {
        this.pagoVenda = pagoVenda;
    }
    public Float getSaldoVenda() {
        return this.saldoVenda;
    }
    
    public void setSaldoVenda(Float saldoVenda) {
        this.saldoVenda = saldoVenda;
    }




}


